# Generated by Django 3.2.19 on 2023-06-07 20:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import traffic.app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Справочник - Типы файлов',
                'verbose_name_plural': 'Справочник - Типы файлов',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Адрес локации для подсчета трафика', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки файла')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Пароль')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней авторизации')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Справочник - Роль пользователяв',
                'verbose_name_plural': 'Справочник - Роль пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Файл', models.FileField(upload_to=traffic.app.utils.get_file_path)),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название файла')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки файла')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_file_type', to='app.filetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_files', to='app.user')),
            ],
            options={
                'verbose_name': 'Пользовательский файл',
                'verbose_name_plural': 'Пользовательские файлы',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='app.usergroup'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало периода подсчёта')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец периода подсчёта')),
                ('JSON данные', models.TextField(blank=True, null=True)),
                ('Локация, на которой ведэтся подсчет', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_report', to='app.location')),
            ],
            options={
                'verbose_name': 'Отчёт по анализу трафика',
                'verbose_name_plural': 'Отчёты по анализу трафика',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='Администратор',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_admin', to='app.user'),
        ),
        migrations.AddField(
            model_name='location',
            name='Клиент',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='app.user'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Фокусное расстояние', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('Кол-во адров в секунду', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('name', models.CharField(max_length=50)),
                ('Локация, на которой установлена камера', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_camera', to='app.location')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
    ]
