# Generated by Django 3.2.19 on 2023-06-10 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230610_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_date',
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подсчёта'),
        ),
    ]
