# Generated by Django 3.2.19 on 2023-06-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230611_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_file_admin', to='app.status', verbose_name='Статус'),
        ),
    ]
