# Generated by Django 3.2.19 on 2023-06-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userfiles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='videofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_video', to='app.userfiles', verbose_name='Видеофайл'),
        ),
    ]
