# Generated by Django 3.2.19 on 2023-06-12 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_report_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_status', to='app.status', verbose_name='Статус'),
        ),
    ]
